### ISSUE TITLE
Options JSON looks weird when populated

### ISSUE THREAD

**Issue by darvid7** [telstra/openapi-platform#73]
![screen shot 2018-09-07 at 11 39 36 pm](https://user-images.githubusercontent.com/11433468/45222406-d8470780-b2f7-11e8-9783-2c654f59e952.png)

**Comment by darvid7** [comment]
https://github.com/telstra/openapi-platform/blob/cbfeb6dfd1dafa189c671ad06fbf7c266f602c93/packages/frontend-dist/src/ValidatedFormStore.tsx#L170 

Might be related

**Comment by calebj0seph** [comment]
There is no issue here, you're passing an object into a form which expects a string.
